### ISSUE TITLE
update 1.8.1.0 is broken on linux

### ISSUE THREAD

**Issue by Caliel666** [akira0245/MidiBard#29]
hello, i've been using midibard for the past month on linux and the previous version 1.8.0.3 worked flawlessly for me, however, when updating to 1.8.1.0 it crashes my game and can't get past the title screen with the following error:

![image](https://user-images.githubusercontent.com/38433434/137588484-2d1addbd-9f5e-4aa8-9666-8b692ff351b1.png)

and from my log:

> [ERR] [LOCALPLUGIN] Error while loading MidiBard
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.BadImageFormatException: Bad IL range.
   at ‪⁬‏‪⁫⁭‎⁬‪‫‬⁬⁫‌‫⁬‎⁬‭⁪‭⁬⁯‏⁬‪⁬⁯‍‬​‫⁭⁫‫‎​‎‪(Byte[] )
   at .cctor()
   --- End of inner exception stack trace ---
   at MidiBard.MidiBard..ctor(DalamudPluginInterface pi)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.Create(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 95
   at Dalamud.Plugin.Internal.LocalPlugin.Load(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\LocalPlugin.cs:line 321
  [FTL] Unhandled exception on AppDomain
System.NullReferenceException: Object reference not set to an instance of an object.
   at MidiBard.MidiBard.FreeUnmanagedResources() in C:\Users\Jane\source\repos\MidiBard\Midibard\MidiBard.cs:line 246
   at MidiBard.MidiBard.Finalize() in C:\Users\Jane\source\repos\MidiBard\Midibard\MidiBard.cs:line 286`

could you take a look into it? sorry for the trouble

  
[dalamud.log](https://github.com/akira0245/MidiBard/files/7357609/dalamud.log)

**Comment by Caliel666** [comment]
yes, latest 1.8.1.2 works, thank you for replying anyway and thank you for making this plugin!
